### ISSUE TITLE
v1.4.0 not available

### ISSUE THREAD

**Issue by zianazhao** [sigstore/cosign-installer#93]
**Question**

I have been using v1.4.0, but it is suddenly unavailable, the error message is as follows, what should I do?

**Comment by zianazhao** [comment]
Generating ephemeral keys...
Retrieving signed certificate...
client.go:194: root pinning is not supported in Spec 1.0.19
Error: signing [ghcr.io/tencentyun/tencentcloud-exporter@sha256:c625a9bc2a9351c4f1c3b5756cxxxx4ae53efe1d406bc8af3ab6ae6f5[64](https://github.com/tencentyun/tencentcloud-exporter/runs/8105xxxxx627?check_suite_focus=true#step:8:65)]: getting signer: getting key from Fulcio: verifying SCT: unmarshal: unexpected end of JSON input
main.go:46: error during command execution: signing [ghcr.io/tencentyun/tencentcloud-exporter@sha256:c625a9bc2a9351c4f1c3b5756cbe4fxxxxxe53efe1d406bc8af3ab6ae6f564]: getting signer: getting key from Fulcio: verifying SCT: unmarshal: unexpected end of JSON input
Error: Process completed with exit code 1.

**Comment by zianazhao** [comment]
I configured like this：
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@1e95c1de343b5b0c23352d6417ee3e48d5bcd422
        with:
          cosign-release: 'v1.4.0'

**Comment by cpanato** [comment]
@zianazhao please update to the latest release available, if you use the keyless approach to sign things, version 1.4.0 and below will not work with Fulcio anymore.

**Comment by zianazhao** [comment]
Hello, after I updated to v1.11.1, I got the following error:

**Comment by zianazhao** [comment]
@cpanato 
Hello, after I updated to v1.11.1, I got Successfully verified SCT，but I got the following error:
Error: signing [ghcr.io/zianazhao/tencentcloud-exporter-1@sha256:2b31cd3bc2deb2c749ea6bd7138e86a7ab544a0e3534ad524809b3d58838e097]: accessing image: entity not found in registry
main.go:62: error during command execution: signing [ghcr.io/zianazhao/tencentcloud-exporter-1@sha256:2b31cd3bc2deb2c749ea6bd7138e86a7ab544a0e3534ad524809b3d58838e097]: accessing image: entity not found in registry
Error: Process completed with exit code 1.

**Comment by cpanato** [comment]
looks like this image is not pushed to your registry, you should push it and then sign

**Comment by zianazhao** [comment]
Thank you for your answer, I have solved the problem after I updated the docker version, thank you again
